name: WorkFlow for Building image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
      - "cmd/fluent-watcher/**"

env:
  FB_IMG: 'zhu733756/fluent-bit:v1.8.11'
  FD_IMG: 'zhu733756/fluentd:v1.14.4'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for Fluent Bit and Fluentd
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setting Environment Variables
        run: |
          echo "tag=$(cat VERSION | tr -d " \t\n\r")" >> $GITHUB_ENV 

      - name: Build and Push Image for Fluent Bit
        run: |
          make build-fb-amd64 -e FB_IMG=${{ env.FB_IMG }} && docker push ${{ env.FB_IMG }}

      - name: Build and Push Image for Fluentd
        run: |
          make build-fd-amd64 -e FD_IMG=${{ env.FD_IMG }} && docker push ${{ env.FD_IMG }}